pull_request_rules:
  - name: auto-merge
    conditions:
      - base=main
      - label!=work-in-progress
    actions:
      merge:
        method: squash
        commit_message_template: |
          {{ title }} (#{{ number }})

          {{ body }}
