pull_request_rules:
  - name: automatic update
    conditions:
      - -conflict
      - -draft
    actions:
      update:
  - name: auto merge
    conditions:
      - base=main
      - label!=work-in-progress
    actions:
      merge:
        method: squash
        commit_message_template: |
          {{ title }} (#{{ number }})

          {{ body }}
  - name: delete head branch after merge
    conditions:
      - merged
    actions:
      delete_head_branch:
