pull_request_rules:
  - name: automatic merge for main when CI passes and 1 review and not WIP
    conditions:
      - base=main
      - label!=work-in-progress
    actions:
      merge:
        method: merge
